### ISSUE TITLE
Need screenshots of the app & run instructions 🌻

### ISSUE THREAD

**Issue by manju4ever** [nitinrameshuf/GoAlcoholGo#1]
https://github.com/nitinrameshuf/GoAlcoholGo/blob/98a68549ccddc287a1ed8050696be038565589e2/README.md?plain=1#L1

**Comment by nitinrameshuf** [comment]
Screenshots and demo is on this link: https://youtu.be/lmQFz_T_um0

To run:
1) Open project  on Android emulator and click Run in the emulator to run the app.

**Comment by manju4ever** [comment]
Needed info on README.MD for quick access. Saw the youtube video. It's great. Probably the same link can be added to README.MD :)
