### ISSUE TITLE
Any citation for this logic & why is Z val not being used in detection ? 

### ISSUE THREAD

**Issue by manju4ever** [nitinrameshuf/GoAlcoholGo#2]
https://github.com/nitinrameshuf/GoAlcoholGo/blob/98a68549ccddc287a1ed8050696be038565589e2/app/src/main/java/com/dh/goalcoholgo/stest.java#L81

**Comment by nitinrameshuf** [comment]
This version of code is made for demonstration on the Android emulator. The emulator visually allows rotation on  X and Y axis only. 
In real world scenario , we will need the X,Y and Z axis to measure accurately.

**Comment by manju4ever** [comment]
Thanks bruh.
